name: p312
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=h3060b56_3
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.13=py312h06a4308_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - freetype=2.13.3=h4a9f257_0
  - gcc=12.1.0=h9ea6d83_10
  - gcc_impl_linux-64=12.1.0=hea43390_17
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=12.1.0=h1ec3361_17
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_3
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=h99ab3db_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libopenblas=0.3.30=pthreads_h94d23a6_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsanitizer=12.1.0=ha89aaad_17
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.5=pyhe01879c_0
  - numpy=2.0.1=py312hc5e2394_1
  - numpy-base=2.0.1=py312h0da6c21_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openfst=1.8.3=h84d6215_3
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.2=h26f9b46_0
  - opentelemetry-api=1.30.0=py312h06a4308_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py312hac6e08b_1
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11=3.0.0=pyh9380348_1
  - pybind11-global=3.0.0=pyhf748d72_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pytorch=2.4.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=py312h06a4308_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.8=h1b44611_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.28=h4ee821c_8
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.4.1=py312_cu124
  - torchtriton=3.0.0=py312
  - torchvision=0.19.1=py312_cu124
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - urllib3=2.5.0=py312h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py312h5eee18b_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - beautifulsoup4==4.13.4
      - click==8.3.1
      - colour-demosaicing==0.2.6
      - colour-science==0.4.6
      - contourpy==1.3.0
      - cupy-cuda12x==12.3.0
      - cvvdp==0.5.4
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.8.2
      - exifread==3.0.0
      - fastrlock==0.8.3
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.16.0
      - h5py==3.12.1
      - hdf5storage==0.1.19
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - imageio==2.36.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.8
      - lpips==0.1.4
      - markdown-it-py==4.0.0
      - matlabengine==25.1.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - nvidia-ml-py==12.575.51
      - nvitop==1.5.2
      - opencv-python==4.10.0.84
      - openexr==3.4.4
      - pandas==2.2.3
      - patchify==0.2.3
      - pip==25.1.1
      - protobuf==5.28.2
      - psutil==6.1.0
      - ptflops==0.7.4
      - pyexr==0.5.0
      - pyparsing==3.2.0
      - pytz==2024.2
      - rawpy==0.23.1
      - rich==14.3.2
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scikit-video==1.1.11
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - smmap==5.0.1
      - soupsieve==2.7
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - timm==1.0.11
      - torch-fidelity==0.4.0
      - torchinfo==1.8.0
      - torchmetrics==1.5.0
      - tqdm==4.66.5
      - typer==0.24.0
      - typer-slim==0.24.0
      - tzdata==2024.2
      - wandb==0.18.5
prefix: /home/tedlasai/miniconda3/envs/p312
